package com.delhivery.axle.utils

/**
 * Request Codes for various actions
 */

const val REQCODE_EDIT_ROUTE = 1231
const val REQCODE_BANK_TRANSACTION = 1232
const val REQCODE_ADD_ROUTES = 1233
const val REQCODE_NO_ROUTES = 1234
const val REQCODE_NO_TRIPS = 1235
const val REQCODE_CREATE_FUELCARD = 1236
const val REQCODE_CREATE_ACTIVE_TRIPS = 1237
const val REQCODE_CALL = 1238
const val REQCODE_WALLET_ONBOARDING = 1239
const val REQCODE_UPLOAD_POD = 1240
const val REQCODE_STORAGE = 1241
const val REQCODE_CAMERA = 1242
const val REQCODE_TAKE_PHOTO = 1243
const val REQCODE_GALLERY_PHOTO = 1244
const val REQCODE_UPLOAD_DOCKET = 1245
const val REQCODE_SELECT_CITY = 1246
const val REQCODE_ADD_TRUCK = 1247